language: node_js
node_js:
  - 14
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha --require esm test/helper_generateTilesMap.test.js test/master.test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js